#!/usr/bin/env python3
"""Tutorial agentic TDD loop — stdlib only, no API key.

Runs *inside* the gulyas sandbox: launch it via
`environment/scripts/herdr-agent-firejail --template offline` so the loop
inherits the repo guardrails (Firejail filesystem jail + netfilter DROP +
allowlist proxy + per-task budget). See docs/tutorial-tdd-mobile-loop.md.

For each task in tasks.json, in order: RED (append failing test) ->
GREEN (cumulative src patch) -> REFACTOR (whitespace normalize + rerun).

Each pytest invocation costs 1 loop-budget unit and appends one JSONL audit
line, mirroring the proxy's own budget (429) + access.log shape. The loop
also honours the wrapper env (BUDGET_ID/BUDGET_MAX/HERDR_AGENT/HERDR_WORKTREE)
so `ps` + audit show which jailed task did what.

Usage:
  python3 agentic_loop.py [--show-plan] [--reset] [--budget-max N]
  python3 agentic_loop.py --check-guardrails   # prove the jail holds (offline-safe)
"""
import argparse
import datetime
import json
import os
import socket
import subprocess
import sys
import urllib.request
from pathlib import Path

BASE = Path(__file__).resolve().parent
SRC = BASE / "src" / "todo_store.py"
TESTS = BASE / "tests" / "test_todo_store.py"
TASKS = BASE / "tasks.json"
STATE_DIR = BASE / ".state"
AUDIT = STATE_DIR / "audit.jsonl"
BUDGET_FILE = STATE_DIR / "budget.json"

TEST_HEADER = '''"""Generated by agentic_loop.py — one test per backlog task (RED step)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import pytest

from src.todo_store import TodoStore

'''

# One snippet per task id. Each must FAIL against the previous src version
# and PASS after its GREEN patch. Kept small on purpose: the test *is* the spec.
TEST_SNIPPETS = {
    "t1-add-list": '''
def test_add_and_list_all():
    store = TodoStore()
    a = store.add("Buy milk")
    b = store.add("  Read docs  ")
    assert (a, b) == (1, 2)
    rows = store.list("all")
    assert [r["title"] for r in rows] == ["Buy milk", "Read docs"]
    with pytest.raises(ValueError):
        store.add("   ")
''',
    "t2-toggle": '''
def test_toggle_flips_done():
    store = TodoStore()
    tid = store.add("Buy milk")
    assert store.list("all")[0]["done"] is False
    store.toggle(tid)
    assert store.list("all")[0]["done"] is True
    store.toggle(tid)
    assert store.list("all")[0]["done"] is False
    with pytest.raises(KeyError):
        store.toggle(999)
''',
    "t3-filter": '''
def test_filter_partitions():
    store = TodoStore()
    a = store.add("one")
    b = store.add("two")
    store.toggle(b)
    assert [r["id"] for r in store.list("active")] == [a]
    assert [r["id"] for r in store.list("done")] == [b]
    with pytest.raises(ValueError):
        store.list("bogus")
''',
    "t4-remove-clear": '''
def test_remove_and_clear_done():
    store = TodoStore()
    a = store.add("one")
    b = store.add("two")
    store.remove(a)
    assert [r["id"] for r in store.list("all")] == [b]
    c = store.add("three")
    assert c == 3  # ids never reused
    store.toggle(b)
    assert store.clear_done() == 1
    assert [r["title"] for r in store.list("all")] == ["three"]
    assert store.clear_done() == 0
    with pytest.raises(KeyError):
        store.remove(999)
''',
    "t5-persist": '''
def test_snapshot_round_trip():
    store = TodoStore()
    a = store.add("one")
    b = store.add("two")
    store.toggle(b)
    snap = store.to_dict()
    clone = TodoStore.from_dict(snap)
    assert clone.to_dict() == snap
    assert [r["id"] for r in clone.list("all")] == [a, b]
    assert clone.add("three") == 3  # counter survives the round-trip
''',
}

# Cumulative GREEN patches. FULL_SOURCES[i] passes tasks[:i].
# Index 0 is the starting stub (everything RED); step k writes FULL_SOURCES[k].
FULL_SOURCES = [
    # v0 — stub: every test RED.
    '''"""Gulyas Tasks core — v0 stub (RED). Everything raises, tests prove it."""


class TodoStore:
    def __init__(self):
        self._items = {}
        self._next_id = 1

    def add(self, title):
        raise NotImplementedError

    def toggle(self, item_id):
        raise NotImplementedError

    def list(self, filter="all"):
        raise NotImplementedError

    def remove(self, item_id):
        raise NotImplementedError

    def clear_done(self):
        raise NotImplementedError

    def to_dict(self):
        raise NotImplementedError

    @classmethod
    def from_dict(cls, data):
        raise NotImplementedError
''',
    # v1 — t1 green: add + list all.
    '''"""Gulyas Tasks core — v1: add + list."""


class TodoStore:
    def __init__(self):
        self._items = {}
        self._next_id = 1

    def add(self, title):
        title = title.strip()
        if not title:
            raise ValueError("title must not be blank")
        item_id = self._next_id
        self._next_id += 1
        self._items[item_id] = {"id": item_id, "title": title, "done": False}
        return item_id

    def toggle(self, item_id):
        raise NotImplementedError

    def list(self, filter="all"):
        return [dict(self._items[k]) for k in sorted(self._items)]

    def remove(self, item_id):
        raise NotImplementedError

    def clear_done(self):
        raise NotImplementedError

    def to_dict(self):
        raise NotImplementedError

    @classmethod
    def from_dict(cls, data):
        raise NotImplementedError
''',
    # v2 — t2 green: toggle.
    '''"""Gulyas Tasks core — v2: + toggle."""


class TodoStore:
    def __init__(self):
        self._items = {}
        self._next_id = 1

    def add(self, title):
        title = title.strip()
        if not title:
            raise ValueError("title must not be blank")
        item_id = self._next_id
        self._next_id += 1
        self._items[item_id] = {"id": item_id, "title": title, "done": False}
        return item_id

    def toggle(self, item_id):
        if item_id not in self._items:
            raise KeyError(item_id)
        self._items[item_id]["done"] = not self._items[item_id]["done"]

    def list(self, filter="all"):
        return [dict(self._items[k]) for k in sorted(self._items)]

    def remove(self, item_id):
        raise NotImplementedError

    def clear_done(self):
        raise NotImplementedError

    def to_dict(self):
        raise NotImplementedError

    @classmethod
    def from_dict(cls, data):
        raise NotImplementedError
''',
    # v3 — t3 green: filter.
    '''"""Gulyas Tasks core — v3: + filter."""


class TodoStore:
    def __init__(self):
        self._items = {}
        self._next_id = 1

    def add(self, title):
        title = title.strip()
        if not title:
            raise ValueError("title must not be blank")
        item_id = self._next_id
        self._next_id += 1
        self._items[item_id] = {"id": item_id, "title": title, "done": False}
        return item_id

    def toggle(self, item_id):
        if item_id not in self._items:
            raise KeyError(item_id)
        self._items[item_id]["done"] = not self._items[item_id]["done"]

    def list(self, filter="all"):
        if filter == "all":
            rows = list(self._items.values())
        elif filter == "active":
            rows = [r for r in self._items.values() if not r["done"]]
        elif filter == "done":
            rows = [r for r in self._items.values() if r["done"]]
        else:
            raise ValueError(f"unknown filter: {filter!r}")
        return [dict(r) for r in sorted(rows, key=lambda r: r["id"])]

    def remove(self, item_id):
        raise NotImplementedError

    def clear_done(self):
        raise NotImplementedError

    def to_dict(self):
        raise NotImplementedError

    @classmethod
    def from_dict(cls, data):
        raise NotImplementedError
''',
    # v4 — t4 green: remove + clear_done.
    '''"""Gulyas Tasks core — v4: + remove / clear_done."""


class TodoStore:
    def __init__(self):
        self._items = {}
        self._next_id = 1

    def add(self, title):
        title = title.strip()
        if not title:
            raise ValueError("title must not be blank")
        item_id = self._next_id
        self._next_id += 1
        self._items[item_id] = {"id": item_id, "title": title, "done": False}
        return item_id

    def toggle(self, item_id):
        if item_id not in self._items:
            raise KeyError(item_id)
        self._items[item_id]["done"] = not self._items[item_id]["done"]

    def list(self, filter="all"):
        if filter == "all":
            rows = list(self._items.values())
        elif filter == "active":
            rows = [r for r in self._items.values() if not r["done"]]
        elif filter == "done":
            rows = [r for r in self._items.values() if r["done"]]
        else:
            raise ValueError(f"unknown filter: {filter!r}")
        return [dict(r) for r in sorted(rows, key=lambda r: r["id"])]

    def remove(self, item_id):
        if item_id not in self._items:
            raise KeyError(item_id)
        del self._items[item_id]

    def clear_done(self):
        done = [k for k, v in self._items.items() if v["done"]]
        for k in done:
            del self._items[k]
        return len(done)

    def to_dict(self):
        raise NotImplementedError

    @classmethod
    def from_dict(cls, data):
        raise NotImplementedError
''',
    # v5 — t5 green: snapshot round-trip (final).
    '''"""Gulyas Tasks core — v5 final: + snapshot persistence."""


class TodoStore:
    def __init__(self):
        self._items = {}
        self._next_id = 1

    def add(self, title):
        title = title.strip()
        if not title:
            raise ValueError("title must not be blank")
        item_id = self._next_id
        self._next_id += 1
        self._items[item_id] = {"id": item_id, "title": title, "done": False}
        return item_id

    def toggle(self, item_id):
        if item_id not in self._items:
            raise KeyError(item_id)
        self._items[item_id]["done"] = not self._items[item_id]["done"]

    def list(self, filter="all"):
        if filter == "all":
            rows = list(self._items.values())
        elif filter == "active":
            rows = [r for r in self._items.values() if not r["done"]]
        elif filter == "done":
            rows = [r for r in self._items.values() if r["done"]]
        else:
            raise ValueError(f"unknown filter: {filter!r}")
        return [dict(r) for r in sorted(rows, key=lambda r: r["id"])]

    def remove(self, item_id):
        if item_id not in self._items:
            raise KeyError(item_id)
        del self._items[item_id]

    def clear_done(self):
        done = [k for k, v in self._items.items() if v["done"]]
        for k in done:
            del self._items[k]
        return len(done)

    def to_dict(self):
        return {
            "next_id": self._next_id,
            "items": [dict(self._items[k]) for k in sorted(self._items)],
        }

    @classmethod
    def from_dict(cls, data):
        store = cls()
        store._next_id = int(data["next_id"])
        store._items = {r["id"]: dict(r) for r in data["items"]}
        return store
''',
]


def load_tasks():
    return json.loads(TASKS.read_text())


def load_budget(max_default):
    STATE_DIR.mkdir(exist_ok=True)
    if BUDGET_FILE.exists():
        spent = json.loads(BUDGET_FILE.read_text()).get("spent", 0)
    else:
        spent = 0
    return spent


def audit(task_id, phase, decision, detail=""):
    STATE_DIR.mkdir(exist_ok=True)
    line = {
        "ts": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "task": task_id,
        "phase": phase,
        "decision": decision,
        "detail": detail,
        # Sandbox context injected by herdr-agent-firejail; empty when run raw.
        "budget_id": os.environ.get("BUDGET_ID", ""),
        "agent": os.environ.get("HERDR_AGENT", ""),
        "worktree": os.environ.get("HERDR_WORKTREE", ""),
    }
    with AUDIT.open("a") as f:
        f.write(json.dumps(line) + "\n")


def check_guardrails():
    """Prove the repo guardrails hold. Offline-safe, short timeouts.

    PASS/FAIL verdicts apply only inside the wrapper jail (HERDR_WORKTREE
    set). Outside, probes report INFO so an unjailed shell can never
    "pass" — re-run via run-in-jail.sh for verdicts.
    """
    jailed = bool(os.environ.get("HERDR_WORKTREE"))
    print(f"guardrails [{'JAILED' if jailed else 'UNJAILLED (plain shell)'}] ...")
    verdicts = []

    # 1. filesystem: sibling worktrees must be invisible (wrapper blacklist).
    sib = Path.home() / ".herdr" / "worktrees"
    sib_visible = sib.exists() and any(sib.iterdir())
    if jailed:
        verdicts.append(not sib_visible)
        print(f"[guardrail:filesystem] siblings visible={sib_visible} — "
              + ("PASS" if not sib_visible
                 else "FAIL: inside jail but siblings visible — launch via herdr-agent-firejail"))
    else:
        print(f"[guardrail:filesystem] INFO siblings visible={sib_visible} "
              "(no jail here; compare with the jailed run)")

    # 2. network: direct TCP egress must DROP (netfilter) — expect timeout/refused.
    try:
        s = socket.create_connection(("93.184.216.34", 80), timeout=4)  # example.com
        s.close()
        if jailed:
            verdicts.append(False)
            print("[guardrail:netfilter] FAIL: direct TCP 93.184.216.34:80 CONNECTED inside the jail")
        else:
            print("[guardrail:netfilter] INFO direct TCP connects (no jail here)")
    except OSError as e:
        if jailed:
            verdicts.append(True)
            print(f"[guardrail:netfilter] PASS direct TCP blocked ({e})")
        else:
            print(f"[guardrail:netfilter] INFO direct TCP blocked ({e}) — host network, not the jail")

    # 3. proxy: a fetch via $http_proxy to a non-allowlisted host must 403
    #    (offline template: *every* host 403s; that is the point).
    proxy = os.environ.get("http_proxy") or os.environ.get("HTTP_PROXY", "")
    if not proxy:
        print("[guardrail:proxy] INFO no http_proxy in env — launch via run-in-jail.sh for the proxied path.")
    else:
        try:
            req = urllib.request.Request("http://example.com/")
            with urllib.request.urlopen(req, timeout=8) as r:
                if jailed:
                    verdicts.append(False)
                print(f"[guardrail:proxy] via {proxy} got {r.status} — "
                      "FAIL for offline template (expect 403)")
        except Exception as e:  # HTTPError 403 carries the proxy denial; that is PASS
            msg = str(e)
            if "403" in msg or "domain-not-allowed" in msg:
                if jailed:
                    verdicts.append(True)
                print(f"[guardrail:proxy] denied as designed ({msg[:120]}) — "
                      + ("PASS" if jailed else "INFO (proxy policy holds outside the jail too)"))
            else:
                print(f"[guardrail:proxy] WARN other error: {msg[:160]} (proxy up? port 8890?)")

    if not jailed:
        print("UNJAILLED — re-run inside the jail (run-in-jail.sh) for PASS/FAIL verdicts.")
        return 0
    print("GUARDRAILS: " + ("ALL HOLD" if verdicts and all(verdicts) else "BREACH — SEE NOTES ABOVE"))
    return 0 if verdicts and all(verdicts) else 1


def charge(spent, budget_max, task_id, phase):
    """One pytest run = 1 budget unit. Returns updated spent; exits 2 if empty."""
    if spent >= budget_max:
        audit(task_id, phase, "budget-exhausted", f"spent={spent} max={budget_max}")
        print(f"429 budget-exhausted at {task_id}/{phase} (spent={spent})", file=sys.stderr)
        sys.exit(2)
    spent += 1
    BUDGET_FILE.write_text(json.dumps({"spent": spent, "max": budget_max}))
    return spent


def run_pytest():
    p = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/test_todo_store.py", "-q"],
        cwd=BASE,
        capture_output=True,
        text=True,
    )
    tail = (p.stdout + p.stderr).strip().splitlines()
    tail = "\n".join(tail[-6:])
    return p.returncode, tail


def reset():
    SRC.write_text(FULL_SOURCES[0])
    TESTS.parent.mkdir(parents=True, exist_ok=True)
    TESTS.write_text(TEST_HEADER)
    STATE_DIR.mkdir(exist_ok=True)
    BUDGET_FILE.write_text(json.dumps({"spent": 0}))
    if AUDIT.exists():
        AUDIT.unlink()
    print("reset: src=stub v0, tests=header only, budget=0")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--show-plan", action="store_true")
    ap.add_argument("--reset", action="store_true")
    ap.add_argument("--check-guardrails", action="store_true")
    ap.add_argument("--budget-max", type=int,
                    default=int(os.environ.get("BUDGET_MAX", "50")))
    args = ap.parse_args()

    if args.reset:
        reset()
        return

    if args.check_guardrails:
        sys.exit(check_guardrails())

    tasks = load_tasks()
    if args.show_plan:
        for i, t in enumerate(tasks, 1):
            print(f"{i}. {t['id']} — {t['title']}\n   {t['spec']}")
        print(f"\nLoop per task: RED (append test, pytest must FAIL) -> "
              f"GREEN (src vN, pytest must PASS) -> REFACTOR (rerun, must PASS).")
        return

    if not SRC.exists() or not TESTS.exists():
        reset()
    spent = load_budget(args.budget_max)

    for step, task in enumerate(tasks, 1):
        tid = task["id"]
        print(f"\n=== [{step}/{len(tasks)}] {tid}: {task['title']} ===")

        # RED — append the task's test, expect failure.
        if TEST_SNIPPETS[tid] not in TESTS.read_text():
            TESTS.write_text(TESTS.read_text() + TEST_SNIPPETS[tid])
        spent = charge(spent, args.budget_max, tid, "red")
        rc, tail = run_pytest()
        audit(tid, "red", "fail" if rc else "unexpected-pass", tail.splitlines()[-1] if tail else "")
        print(f"RED rc={rc}\n{tail}")
        if rc == 0:
            print("WARN: RED passed — test does not discriminate. Stopping.", file=sys.stderr)
            sys.exit(1)

        # GREEN — cumulative patch, expect pass.
        SRC.write_text(FULL_SOURCES[step])
        spent = charge(spent, args.budget_max, tid, "green")
        rc, tail = run_pytest()
        audit(tid, "green", "pass" if rc == 0 else "fail", tail.splitlines()[-1] if tail else "")
        print(f"GREEN rc={rc}\n{tail}")
        if rc != 0:
            print("GREEN failed — patch incomplete. Stopping.", file=sys.stderr)
            sys.exit(1)

        # REFACTOR — normalize, rerun full suite, expect pass.
        SRC.write_text(SRC.read_text().rstrip() + "\n")
        spent = charge(spent, args.budget_max, tid, "refactor")
        rc, tail = run_pytest()
        audit(tid, "refactor", "pass" if rc == 0 else "fail", tail.splitlines()[-1] if tail else "")
        print(f"REFACTOR rc={rc}\n{tail}")
        if rc != 0:
            print("REFACTOR broke the suite. Stopping.", file=sys.stderr)
            sys.exit(1)

    print(f"\nDONE: {len(tasks)} tasks green, spent={spent}/{args.budget_max}. "
          f"Audit: {AUDIT.relative_to(BASE)}")


if __name__ == "__main__":
    main()
