"""Generated by agentic_loop.py — one test per backlog task (RED step)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import pytest

from src.todo_store import TodoStore

